# Generated by Django 5.2.6 on 2025-12-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='General', max_length=250, verbose_name='Plataforma / Desarrollador'),
        ),
    ]
